// Gallery originals are multi-MB camera files. Pre-resized JPEG copies live in
// /images/thumbs/{800,1600}/gallery/… (same relative path, .jpg extension),
// generated by scripts/make-thumbs.sh. Non-gallery paths pass through unchanged.
const GALLERY_RE = /^\/images\/gallery\/(.+)\.(jpe?g|png|webp)$/i;

export function thumb(src, width = 800) {
  const match = typeof src === "string" && GALLERY_RE.exec(src);
  return match ? encodeURI(`/images/thumbs/${width}/gallery/${match[1]}.jpg`) : src;
}

export function thumbSrcSet(src) {
  if (typeof src !== "string" || !GALLERY_RE.test(src)) return undefined;
  return `${thumb(src, 800)} 800w, ${thumb(src, 1600)} 1600w`;
}

// Spread onto an <img>: {...responsiveImg(src, "(min-width: 768px) 50vw, 100vw")}
export function responsiveImg(src, sizes) {
  const srcSet = thumbSrcSet(src);
  if (!srcSet) return { src };
  return {
    src: thumb(src),
    srcSet,
    sizes,
    // A photo added without running make-thumbs.sh falls back to its original
    onError: (e) => {
      const img = e.currentTarget;
      if (img.dataset.thumbFallback) return;
      img.dataset.thumbFallback = "1";
      img.removeAttribute("srcset");
      img.src = src;
    },
  };
}
